package co.edu.uniquindio.proyectoFinal.model;

public enum NombreVentana {
		GESTION_RED,
		GESTION_VENDEDOR,
		GESTION_MSJS,
		CANTIDAD_PRODUCTOS,
		TOP_TEN,
		PRODUCTOS_POR_VENDEDOR,
		PRODUCTOS_RED,
		GESTION_PRODUCTOS,
		MIS_PRODUCTOS,
		CHAT;
}
